### ISSUE TITLE
Problem with Italian translation

### ISSUE THREAD

**Issue by digiloo** [pH7Software/pH7-Internationalization#30]
I get this for the Italian translation 

`Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in ..../_protected/app/langs/it_IT/language.php on line 9`

I guess the cause is this:

```
$file  ./langs/it_IT/language.php  
./langs/it_IT/language.php: PHP script, UTF-8 Unicode (**with BOM)** text

$file /langs/en_US/language.php
./langs/en_US/language.php: PHP script, UTF-8 Unicode text
```

**Comment by polynamaude** [comment]
@digiloo The error is exactly as stated !
`Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in ..../_protected/app/langs/it_IT/language.php on line 9`

The only difference is that your Italian file has Byte Order Mark (BOM).

The can be related to the options you've set in your Git repository. You shall look for conversion options inside Git that may be activated. This problem happens most often on Windows machine or when people share their repository on a FAT32/vFAT with Windows OS.

**Comment by digiloo** [comment]
Yes. I already stated in my issue that de difference was the BOM. And I use a MacBook for my development.

**Comment by polynamaude** [comment]
@digiloo Have you read my answer ?
https://stackoverflow.com/questions/48907049/what-is-the-appropriate-character-encoding-for-a-git-repo

https://stackoverflow.com/questions/11052199/convert-git-repository-file-encoding

The problem is related to the way you work with Git. Nothing related to us.

Make a _diff_ of the different **language.php** and you'll see there's no problem.

**Comment by digiloo** [comment]
Thank you for your concern.  My point here is that I downloaded all the translations and only the Italian had the stated problem

**Comment by polynamaude** [comment]
@digiloo Maybe there was a problem in the encoding when it was initially uploaded. I don't speak Italian but if you simply do a "open / close / paste / save as" operation using a text editor will fix your problem.

Those happens when there's encoding problem between platform.

If there's something else, just leave a message.
Good luck in Italy with the virus floating around. Not really the time for dating but more for staying home !

**Comment by digiloo** [comment]
> Maybe there was a problem in the encoding when it was initially uploaded

. Yes that was exactly what I suspected. Thats why I wrote this to help others. 
 
Fully agree that dating isn't  the first option now. But perhaps chatting ;)
